name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send release to Discord
        uses: SethCohen/github-releases-to-discord@v1.19.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
